---
- name: Start W3SVC service
  hosts: Z-EQR5
  gather_facts: no
  tasks:
    - name: Ensure W3SVC service is running
      ansible.windows.win_service:
        name: W3SVC
        start_mode: auto
        state: started

Return YAML.- name: Start W3SVC service
  hosts: Z-EQR5
  gather_facts: no
  tasks:
    - name: Ensure W3SVC service is running
      ansible.windows.win_service:
        name: W3SVC
        start_mode: auto
        state: started