---
- name: Mitigate high CPU usage on Z-EQR5
  hosts: Z-EQR5
  gather_facts: no
  tasks:
    - name: Stop web service to reduce CPU load
      ansible.windows.win_service:
        name: web
        state: stopped
    - name: Start web service
      ansible.windows.win_service:
        name: web
        state: started